blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'blog'

urlpatterns = [
    path('posts', views.post_list, name="post_list"),
    path('post/<int:id>/', views.post_detail, name="post_detail"),
    path('post/add_post/<int:id>', views.add_post, name="add_post"),
    path('post/add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('login/', views.log_in, name='login'),
    path('search/', views.post_search, name='post_search'),
    path('delete_post/<int:id>', views.delete_post, name='delete_post'),
    path('delete_post/<int:id>/confirmed', views.delete_post_confirmed, name='delete_post_confirmed'),
    path('add_account/', views.add_account, name='add_account'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('profile/<int:id>/edit_profile', views.edit_profile, name='edit_profile'),
    path('profile/<int:id>/edit_profile/delete_account', views.delete_account, name='delete_account'),
    path('profile/<int:id>/edit_profile/delete_account/confirmed', views.delete_account_confirmed,
         name='delete_account_confirmed'),
    path('home_screen', views.home_screen, name='home_screen'),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

 ]

twiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django_resized import ResizedImageField


# Create your models here.

class Post(models.Model):
    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)

    class Status(models.TextChoices):
        DRAFT = ("draft", "Draft")
        REJECTED = ("rejected", "Rejected")
        PUBLISHED = ("published", "Published")

    auther = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.CharField(max_length=250)

    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublishedManager()

    status = models.CharField(max_length=250, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    status = models.BooleanField(default=False)
    auther = models.CharField(max_length=250)
    text = models.TextField(max_length=500)
    create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['create']
        indexes = [
            models.Index(fields=['create'])
        ]

    def __str__(self):
        return self.auther


def image_sorter(instance, filename):
    return f"post_images/{instance.create.year}/{filename}"


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images")
    create = models.DateTimeField(auto_now_add=True)
    image = ResizedImageField(upload_to=image_sorter, quality=70)
    title = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['create']
        indexes = [
            models.Index(fields=['create'])
        ]

    def __str__(self):
        if self.title:
            return self.title
        else:
            self.title = self.image.name
            return self.title

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    image = forms.ImageField(allow_empty_file=True, label='add image', widget=forms.FileInput(
        attrs={'placeholder': 'add image', 'class': 'add-image'}))

    class Meta:
        model = Post
        fields = ['title', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'add-post-title'}),
            'description': forms.Textarea(attrs={'class': 'add-post-description'}),
        }


class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'username-input', 'placeholder': 'username'}), label='username')
    password = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'password-input', 'placeholder': 'password'}), label='password')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['auther', 'text']
        widgets = {
            'auther': forms.TextInput(attrs={'class': 'add-comment-auther'}),
            'text': forms.Textarea(attrs={'class': 'add-comment-text'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()


class AddAccountForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'username', 'class': 'username-input'}))
    password = forms.CharField(min_length=8, widget=forms.PasswordInput(
        attrs={'placeholder': 'password', 'class': 'password-input'}))
    confirm_password = forms.CharField(min_length=8, widget=forms.PasswordInput(
        attrs={'placeholder': 'confirm password', 'class': 'password-input'}))


class EditProfileForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'new username', 'class': 'new-username'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'new password', 'class': 'new-password'}))
    confirm_password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'confirm new password', 'class': 'new-password'}))

blog/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.contrib.postgres.search import TrigramSimilarity


# Create your views here.


def post_list(request):
    posts = Post.published.all()
    context = {
        'posts': posts,
    }
    return render(request, "blog/post_list.html", context)


def filtering(text: str):
    words = ['fuck', 'shet', 'fuck you']
    for word in words:
        if word in text:
            return False
    return True


def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    comment_form = CommentForm()
    comments = post.comments.filter(status=True)
    user_login = request.user
    same_person = (post.auther_id == user_login)
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'same_person': same_person,
    }
    return render(request, "blog/post_detail.html", context)


@login_required
def add_post(request, id):
    context = {}
    word_filter = True
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        user = User.objects.get(id=id)
        posts = Post.published.all()
        if form.is_valid():
            cd = form.cleaned_data
            if filtering(cd['description']) and filtering(cd['title']):
                post_obj = Post.objects.create(auther_id=id)
                post_obj.title = cd['title']
                post_obj.description = cd['description']
                post_obj.status = Post.Status.PUBLISHED
                post_obj.save()
                Image.objects.create(post=post_obj, image=form.cleaned_data['image'])
                post_obj.save()
            else:
                form = PostForm()
                word_filter = False
                context = {
                    'form': form,
                    'word_filter': word_filter,
                }
                return render(request, "forms/add_post.html", context)
            context = {
                'username': user.username,
                'id': id,
                'posts': posts
            }
            return render(request, 'blog/post_list.html', context)

    else:
        form = PostForm()
        context = {
            'form': form,
            'word_filter': word_filter,
        }
    return render(request, "forms/add_post.html", context)


def log_in(request):
    user_available = False
    password_correct = False
    posts = Post.published.all()
    context = {}
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            f_username = cd['username']
            f_password = cd['password']
            try:
                user = get_object_or_404(User, username=f_username)
            except:
                login_form = LoginForm()
                context = {
                    'login_form': login_form,
                    'user_available': user_available,
                    'password_correct': password_correct,
                }
                return render(request, 'forms/login.html', context)

            if user.check_password(f_password):
                login(request, user)
                context = {
                    'username': user.username,
                    'posts': posts,
                    'id': user.id,
                }

                return render(request, 'blog/post_list.html', context)
            else:
                login_form = LoginForm()
                context = {
                    'login_form': login_form,
                    'user_available': True,
                    'password_correct': password_correct,
                }
                return render(request, 'forms/login.html', context)
    else:
        login_form = LoginForm()
        context = {
            'login_form': login_form,
            'user_available': True,
            'password_correct': True,
        }
    return render(request, 'forms/login.html', context)


def add_comment(request, post_id):
    word_filter = True
    if request.method == "POST":
        post = get_object_or_404(Post, id=post_id)
        comment = None
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            if filtering(comment.text) and filtering(comment.auther):
                comment.status = True
                comment.post = post
                comment.save()
            else:
                word_filter = False
                comment_form = CommentForm()
                context = {
                    'comment_form': comment_form,
                    'word_filter': word_filter
                }
                return render(request, 'forms/add_comment.html', context)

        context = {
            'post': post,
            'comment_form': comment_form,
            'comment': comment,
            'word_filter': word_filter
        }
        return render(request, 'forms/add_comment.html', context)
    else:
        comment_form = CommentForm()
        context = {
            'comment_form': comment_form,
            'word_filter': word_filter
        }
    return render(request, 'forms/add_comment.html', context)


def post_search(request):
    query = None
    posts_results = []
    images_results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)) \
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            results3 = Image.objects.annotate(similarity=TrigramSimilarity('title', query)) \
                .filter(similarity__gt=0.1)
            results4 = Image.objects.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            posts_results = (results1 | results2).order_by('-similarity')
            images_results = (results3 | results4).order_by('-similarity')
    context = {
        'query': query,
        'posts_results': posts_results,
        'images_results': images_results,
    }
    return render(request, 'blog/post_search.html', context)


@login_required
def delete_post(request, id):
    context = {
        'id': id,
    }
    return render(request, 'blog/delete_post.html', context)


@login_required
def delete_post_confirmed(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    posts = Post.published.all()
    user = User.objects.get(id=post.auther_id)

    context = {
        'posts': posts,
        'username': user.username,
        'id': user.id,
    }
    return render(request, "blog/post_list.html", context)


def add_account(request):
    context = {}
    username_available = False
    password_match = True
    posts = Post.published.all()
    if request.method == 'POST':
        form = AddAccountForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            for user in User.objects.all():
                if user.username == cd['username']:
                    username_available = True
                    form = AddAccountForm()
                    context = {
                        'form': form,
                        'username_available': username_available,
                        'password_match': password_match,
                    }
                    return render(request, 'forms/add_account.html', context)

            if cd['password'] == cd['confirm_password']:
                user = User.objects.create()
                user.username = cd['username']
                user.set_password(cd['password'])
                user.save()
                context = {
                    'username': user.username,
                    'id': user.id,
                    'posts': posts,
                }
                return render(request, 'blog/post_list.html', context)
            else:
                password_match = False
                form = AddAccountForm()
                context = {
                    'form': form,
                    'username_available': username_available,
                    'password_match': password_match,
                }
                return render(request, 'forms/add_account.html', context)
    else:
        form = AddAccountForm()
        context = {
            'form': form,
            'username_available': username_available,
            'password_match': password_match,
        }
    return render(request, 'forms/add_account.html', context)


@login_required
def profile(request, id):
    user = User.objects.get(id=id)
    posts = Post.published.filter(auther_id=id)
    context = {
        'user': user,
        'posts': posts,
        'id': id,
    }
    return render(request, 'blog/profile.html', context)


@login_required
def edit_profile(request, id):
    context = {}

    if request.method == 'POST':
        form = EditProfileForm(request.POST)
        user = User.objects.get(id=id)
        if form.is_valid():
            cd = form.cleaned_data
            user.username = cd['username']
            if cd['confirm_password'] == cd['password']:
                posts = Post.published.filter(auther_id=id)
                user.set_password(cd['password'])
                user.save()
                context = {
                    'id': id,
                    'user': user,
                    'posts': posts,
                }
                return render(request, 'blog/profile.html', context)
            else:
                form = EditProfileForm()

blog/templates/blog/delete_account.html
{% extends "parent/base_template.html" %}
{% block title %} Delete Post{% endblock %}
{% block content%}
    <div class="rusure">
        <p style="text-align: justify">Are you sure you want to delete {{ user.username }} account with {{ posts.count }} posts{{ posts.count|pluralize }}?</p>
        <div class="yes-or-no">
            <a href="{% url 'blog:delete_account_confirmed' id%}" class="yes">yes</a>
            <a href="{% url 'blog:profile' id %}" class="no">no</a>
        </div>
    </div>
{% endblock %}

blog/templates/blog/delete_post.html
{% extends "parent/base_template.html" %}
{% block title %} Delete Post{% endblock %}
{% block content%}
    <div class="rusure">
        <p style="text-align: justify">Are you sure you want to delete this post?</p>
        <div class="yes-or-no">
            <a href="{% url 'blog:delete_post_confirmed' id%}" class="yes">yes</a>
            <a href="{% url 'blog:post_detail' id %}" class="no">no</a>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "parent/base_template.html" %}
{% block title %} Post Detail{% endblock %}
{% block content%}
    <div class="post-tools">
        <h1 class="post-title">{{ post.title }}</h1>
        {% if same_person %}
            <a href="{% url 'blog:delete_post' post.id %}" class="delete-post">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="delete-post-icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
            </svg>
        </a>
        {% endif %}
    </div>

{#    {% for image in post.images.all %}#}
{#        <img src="{{ image.image.url }}" alt="{{ image.title }}">#}
{#    {% endfor %}#}
    <div class="post-description">
    <p>{{ post.description }}</p>
    {% if post.images %}
        {% for image in post.images.all %}
            <img src="{{ image.image.url }}" alt="image" class="post-image">
        {% endfor %}
    {% endif %}
    </div>

    <h4 class="auther">{{ post.auther }}</h4>
    <div class="ccac">
        {% with comments.count as c_count %}
        <a href="{% url 'blog:add_comment' post.id%}" class="add-comment">Add comment</a>
        <p class="c_count">{{ c_count }} comment{{ c_count|pluralize }}</p>
        {% endwith %}
    </div>

    {% for comment in comments %}
        <div class="comments">
        <p class="p-auther">{{ comment.auther }}</p>
        <p class="p-text">{{ comment.text|linebreaks }}</p>
        </div>
    {% empty %}
        <p class="empty">there is no comments</p>
    {% endfor %}


{% endblock %}

blog/templates/blog/post_list.html
{% extends "parent/base_template.html" %}
{% load blog_tags %}
{% block title %} Post List{% endblock %}
{% block content%}

    <h1 class="posts-title">Posts</h1>
    <p class="prolific_users_p">Prolific Users</p>

    <div class="prolific_users">
    {% prolific_users as p_users %}
    {% for user in p_users %}
        <a class="p_user">{{ user.username }} with {{ user.p_users }} post{{user.p_users|pluralize}}</a>
    {% endfor %}
    </div>

    <div class="buttons">
    {% if username %}
        <a href="{% url 'blog:add_post' id %}" class="add-post">Add Post</a>
        <a href="{% url 'blog:profile' id %}" class="username">{{ username }}</a>
        <a href="{% url 'blog:post_list' %}" class="logout">Logout</a>
    {% else %}
        <a href="{% url 'blog:login' %}" class="login">login</a>
    {% endif %}
    </div>

    <div class="posts">
    {% for post in posts %}
        <div class="post">
            <a href="{% url 'blog:post_detail' post.id%}" class="title_in_list"><b>{{ post.title }}</b></a>
            <p class="text">{{ post.description|truncatewords:4}}</p>
{#            <img src="{{ post.images.first.image.url }}" alt="{{ post.images.first.title }}">#}
        </div>
    {% empty %}
        <p class="no-post">no post founded!</p>
    {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post_search.html
{% extends "parent/base_template.html" %}

{% block title %} Search results{% endblock %}
{% block content%}
    {% if query %}
        <p class="count-results">count of results for searching {{ query }} is : {{ posts_results.count|add:images_results.count}}</p>
        <div class="posts">
        {% for result in posts_results %}
            <div class="post">
            <a href="{% url 'blog:post_detail' result.id%}" class="title_in_list">{{ result.title }}</a>
            <p class="text">{{result.description|truncatewords:4}}</p>
            </div>
            {% empty %}
                <p class="no-post">no results in posts founded!</p>
        {% endfor %}
        </div>
        <div class="posts">
        {% for result in images_results %}
            <div class="post">
            <a href="{% url 'blog:post_detail' result.post_id%}" class="title_in_list">{{ result.title }}</a>
            <p class="text">{{result.description|truncatewords:4}}</p>
            </div>
            {% empty %}
                <p class="no-post">no results in images founded!</p>
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/profile.html
{% extends "parent/base_template.html" %}
{% block title %} Profile{% endblock %}
{% block content%}
    <h1 style="text-align: center; color: bisque" class="prof-title">Profile</h1>

    <div class="prof">
        <div class="prof-username">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="user-icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
            </svg>
            <p>{{ user.username }}</p>
        </div>
        <p class="prof-post-number">number of posts: {{ user.posts.count }}</p>
        <a href="{% url 'blog:edit_profile' id %}" class="edit-profile">edit profile</a>
    </div>
    <div class="posts">
    {% for post in posts %}
        <div class="post">
            <a href="{% url 'blog:post_detail' post.id%}" class="title_in_list"><b>{{ post.title }}</b></a>
            <p class="text">{{ post.description|truncatewords:4}}</p>
        </div>
    {% empty %}
        <p class="no-post">no post founded!</p>
    {% endfor %}
    </div>
{% endblock %}